### ISSUE TITLE
Don't get any output

### ISSUE THREAD

**Issue by florianib** [ChrisTheCoolHut/Instruction-Stomp#1]
Hello!

I am trying to get your tool to work, but unfortunately it doesn't do anything.
I am starting the celery worker with following command: `celery -A lib.celery_tasks worker --loglevel=info` and want to try your example with: `python InstStomp.py -g -c 30  --stdin challenges/wyvern_c85f1be480808a9da350faaa6104a19b`

Output of the worker:
````
celery -A lib.celery_tasks worker --loglevel=info
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
 
 -------------- celery@kali v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Linux-4.19.0-kali4-amd64-x86_64-with-Kali-kali-rolling-kali-rolling 2019-05-10 21:13:45
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         CeleryTask:0x7f63bb6b9750
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     rpc://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . lib.celery_tasks.run_qemu_command

[2019-05-10 21:13:45,287: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2019-05-10 21:13:47,314: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...
````

And I don't get any output for the python script.

I am working on Kali Linux 64 bit.

Have I done anything wrong here?

**Comment by ChrisTheCoolHut** [comment]
Hey 0x00xx, it looks like it can't connect to rabbitmq. I forgot to include an install line for installing rabbitmq as a message broker.

Installing rabbitmq-server should fix your problem.

```
sudo apt-get install rabbitmq-server
```

Once installed, rerun your celery worker command.

Should be fixed in e3381a92f886b515beae05a9733dc884e052077e . Thanks for the issue!

**Comment by florianib** [comment]
Hello Chris and thanks for the fast answer!

It is indeed fixed, after installing rabbitmq-server and starting the service.
But I have another issue now:

```
python InstStomp.py -g -c 30  --stdin challenges/wyvern_c85f1be480808a9da350faaa6104a19b
[~] Running input length check:   0%|                                                    | 0/30 [00:00<?, ?it/s]
[]
Traceback (most recent call last):
  File "InstStomp.py", line 148, in <module>
    main()
  File "InstStomp.py", line 145, in main
    solve_input_len(args.File, args.inputCheckCount, args.stdin)
  File "InstStomp.py", line 117, in solve_input_len
    input_len = max(results,key=itemgetter(1))[0]
ValueError: max() arg is an empty sequence
```

```celery -A lib.celery_tasks worker --loglevel=info
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
 
 -------------- celery@kali v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Linux-4.19.0-kali4-amd64-x86_64-with-Kali-kali-rolling-kali-rolling 2019-05-10 22:01:37
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         CeleryTask:0x7fb53f091750
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     rpc://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . lib.celery_tasks.run_qemu_command

[2019-05-10 22:01:37,538: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2019-05-10 22:01:37,560: INFO/MainProcess] mingle: searching for neighbors
[2019-05-10 22:01:38,631: INFO/MainProcess] mingle: all alone
[2019-05-10 22:01:38,685: INFO/MainProcess] celery@kali ready.
[2019-05-10 22:01:47,042: INFO/MainProcess] Received task: lib.celery_tasks.run_qemu_command[bedca771-e613-4b01-a4c2-8692a67a304d]  
[2019-05-10 22:01:47,065: INFO/MainProcess] Received task: lib.celery_tasks.run_qemu_command[7ac8d7dc-7174-4f99-819b-aa163d96c976]  
[2019-05-10 22:01:47,075: INFO/MainProcess] Received task: lib.celery_tasks.run_qemu_command[662e07fe-c4b6-4c16-aa89-a641b187ccf6]  
[2019-05-10 22:01:47,078: INFO/MainProcess] Received task: lib.celery_tasks.run_qemu_command[7ce366dd-3fcd-432e-9483-d750b74a8efb]  
[2019-05-10 22:01:47,090: INFO/MainProcess] Received task: lib.celery_tasks.run_qemu_command[582aaaa9-7077-44db-9f7b-acead81b9d0a]  
[2019-05-10 22:01:47,078: ERROR/ForkPoolWorker-3] Task lib.celery_tasks.run_qemu_command[bedca771-e613-4b01-a4c2-8692a67a304d] raised unexpected: TypeError("descriptor 'encode' requires a 'str' object but received a 'unicode'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/Instruction-Stomp/lib/celery_tasks.py", line 14, in run_qemu_command
    content = str.encode(content)
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'
```

Any solution for that one?

**Comment by ChrisTheCoolHut** [comment]
Figured it out, you're running using python2! 

Swap your pip install to pip3 and your ```python InstStomp.py``` to ```python3 InstStomp.py```

I'll make a note in the readme about using python3. 

To have celery work for python3 you'll need to either uninstall celery for python2 or run the command as ```python3 -m celery``` instead of ```celery```

**Comment by florianib** [comment]
Works, thanks for the support! :)
